apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: goop-wildfly
    name: goop-wildfly-dc
  spec:
    replicas: 1
    selector:
      deploymentconfig: goop-wildfly-dc
    template:
      metadata:
        labels:
          app: goop-wildfly
          deploymentconfig: goop-wildfly-dc
      spec:
        containers:
        - image: goop-wildfly
          name: goop-wildfly
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - name: config-volume
            mountPath: /tmp/
        volumes:
          - name: config-volume
            configMap:
              name: application.properties
              items:
              - key: application.properties
                path: app/application.properties
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - goop-wildfly
        from:
          kind: ImageStreamTag
          name: goop-wildfly:latest
      type: ImageChange
    - type: ConfigChange

